spring:
  application:
    name: redbank
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

scheduler:
  reconciliation:
    cron: "0 0 0 * * *"
  registration-cleanup:
    cron: "0 0 3 * * *"
  stale-transaction:
    cron: "0 */15 * * * *"
  token-revocation:
    cron: "0 0 2 * * *"

management:
  tracing:
    sampling:
      probability: 1.0