package com.redmath.redbank.audit;

public enum AuditAction {
  REGISTRATION_APPROVED,
  REGISTRATION_REJECTED,
  USER_CREATED,
  USER_UPDATED,
  USER_ACTIVATED,
  USER_DEACTIVATED,
  ACCOUNT_CREATED,
  ACCOUNT_ACTIVATED,
  ACCOUNT_FROZEN,
  ACCOUNT_CLOSED,
  TRANSACTION_REVERSED,
  ADMIN_DEPOSIT_RECORDED,
  LOCATION_RISK_ASSESSED,
  TRANSACTION_APPROVED,
  TRANSACTION_REJECTED
}
